---
# Mixed Models: General Case 

Consider the Linear Regression with $m$ marketing activities and $i$ regions:

\begin{equation}
Y_{it} = \beta_0 + \sum_{j=0}^{m} \beta_{j} X_{ijt} + \sum_{j=0}^{m} \beta^{(i)}_{j} X_{ijt}  + \varepsilon_{it}
\end{equation}

where: 

* $t$ is a unit of time (eg. week, month, etc)
* $Y_{it}$ is the KPI of interest (eg. Sales in Chicago in March)
* $X_j$ is the marketing spend for the $j$th marketing variable (eg. TV ads, Youtube Ads, Google Ads, etc)
* $\beta_j$ is the average incremental effect of one unit of $X_{jt}$
* $\beta^{(i)}_j$ is the deviation from the average incremental effect of one unit of $X_{jt}$ in region $i$
* $\varepsilon_{it}$ is the modelling error, i.e difference between predicted and actual values of the KPI

---
class: font130
# Interpreting Mixed Models

Consider an example from the 2 marketing activity $\times$ 2 region model:

* $\hat{\beta}_1 = 0.5$, $\hat{\beta}_2 = 0.75$
* $\hat{\beta}^{\text{Chicago}}_1 = 0.5$, $\hat{\beta}^{\text{Chicago}}_2 = 0.25$
* $\hat{\beta}^{\text{SanFran}}_1 = -0.25$, $\hat{\beta}^{\text{SanFran}}_2 = -0.5$

What do these estimates mean?


In class ...

---
# A Two Activity, Two Region Mixed Model

Suppose only spend on Facedb Ads and TV Ads, KPI is Sales.

Two Regions: National data, want different effects for Chicago and San Francisco.

Form a regression model:

\begin{align}
\text{Sales}_{it} = \beta_0 &+ \underbrace{\beta_{1F} \text{YouTube Ad Spending}_{it} + \beta_{2F} \text{TV Ad Spending}_{it}}_{\text{Average Impacts}} \\
                            &+ \underbrace{\beta_{1\text{Chicago}} \text{YouTube Ad Spending}_{it} + \beta_{2\text{Chicago}} \text{TV Ad Spending}_{it}}_{\text{Chicago's Deviations}} \\
                            &+ \underbrace{\beta_{1\text{San Fran}} \text{YouTube Ad Spending}_{it} + \beta_{2\text{San Fran}} \text{TV Ad Spending}_{it}}_{San Franciso's Deviations} \\
                            &+ \varepsilon_{it}
\end{align}

Then: 

* Average Impacts: $\beta_{jF}$
* Chicago Impacts: $\beta_{jF}$ + $\beta_{j\text{Chicago}}$
* San Franciso Impacts: $\beta_{jF}$ + $\beta_{j\text{San Franciso}}$ 

